server:
  port: 9999

management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info"

spring:
  application:
    name: flatbuffer-demo
  main:
    banner-mode: off
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  mongodb:
    url: "mongodb://localhost:27017/"


logging:
  level:
    org.springframework.web: DEBUG
