// automatically generated by the FlatBuffers compiler, do not modify

package Complaince.Document;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Description extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Description getRootAsDescription(ByteBuffer _bb) { return getRootAsDescription(_bb, new Description()); }
  public static Description getRootAsDescription(ByteBuffer _bb, Description obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Description __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String title() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String department() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer departmentAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer departmentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String uniqueCode() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uniqueCodeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer uniqueCodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createDescription(FlatBufferBuilder builder,
      int titleOffset,
      int departmentOffset,
      int unique_codeOffset) {
    builder.startTable(3);
    Description.addUniqueCode(builder, unique_codeOffset);
    Description.addDepartment(builder, departmentOffset);
    Description.addTitle(builder, titleOffset);
    return Description.endDescription(builder);
  }

  public static void startDescription(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(0, titleOffset, 0); }
  public static void addDepartment(FlatBufferBuilder builder, int departmentOffset) { builder.addOffset(1, departmentOffset, 0); }
  public static void addUniqueCode(FlatBufferBuilder builder, int uniqueCodeOffset) { builder.addOffset(2, uniqueCodeOffset, 0); }
  public static int endDescription(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Description get(int j) { return get(new Description(), j); }
    public Description get(Description obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

