// automatically generated by the FlatBuffers compiler, do not modify

package Complaince.Document;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Document extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Document getRootAsDocument(ByteBuffer _bb) { return getRootAsDocument(_bb, new Document()); }
  public static Document getRootAsDocument(ByteBuffer _bb, Document obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Document __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public Description description() { return description(new Description()); }
  public Description description(Description obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public Complaint complaint() { return complaint(new Complaint()); }
  public Complaint complaint(Complaint obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createDocument(FlatBufferBuilder builder,
      int idOffset,
      int nameOffset,
      int descriptionOffset,
      int complaintOffset) {
    builder.startTable(4);
    Document.addComplaint(builder, complaintOffset);
    Document.addDescription(builder, descriptionOffset);
    Document.addName(builder, nameOffset);
    Document.addId(builder, idOffset);
    return Document.endDocument(builder);
  }

  public static void startDocument(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(2, descriptionOffset, 0); }
  public static void addComplaint(FlatBufferBuilder builder, int complaintOffset) { builder.addOffset(3, complaintOffset, 0); }
  public static int endDocument(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishDocumentBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedDocumentBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Document get(int j) { return get(new Document(), j); }
    public Document get(Document obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

