// automatically generated by the FlatBuffers compiler, do not modify

package Complaince.Document;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Owner extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Owner getRootAsOwner(ByteBuffer _bb) { return getRootAsOwner(_bb, new Owner()); }
  public static Owner getRootAsOwner(ByteBuffer _bb, Owner obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Owner __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String surname() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer surnameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer surnameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public Address address() { return address(new Address()); }
  public Address address(Address obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createOwner(FlatBufferBuilder builder,
      int nameOffset,
      int surnameOffset,
      int addressOffset) {
    builder.startTable(3);
    Owner.addAddress(builder, addressOffset);
    Owner.addSurname(builder, surnameOffset);
    Owner.addName(builder, nameOffset);
    return Owner.endOwner(builder);
  }

  public static void startOwner(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addSurname(FlatBufferBuilder builder, int surnameOffset) { builder.addOffset(1, surnameOffset, 0); }
  public static void addAddress(FlatBufferBuilder builder, int addressOffset) { builder.addOffset(2, addressOffset, 0); }
  public static int endOwner(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Owner get(int j) { return get(new Owner(), j); }
    public Owner get(Owner obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

