// automatically generated by the FlatBuffers compiler, do not modify

package Complaince.Document;

public final class Status {
  private Status() { }
  public static final short OK = 0;
  public static final short NEW = 1;
  public static final short RESERVED = 2;
  public static final short CANCELLED = 3;

  public static final String[] names = { "OK", "NEW", "RESERVED", "CANCELLED", };

  public static String name(int e) { return names[e]; }
}

